### ISSUE TITLE
Colores de correcto e incorrecto

### ISSUE THREAD

**Issue by cabudui** [jfraan/TriviaIA#4]
Creo que podrias poner un color rojo como incorrecto y uno celeste como correcto :)

![image](https://user-images.githubusercontent.com/113648766/190837642-e2d52e51-afdb-404e-bce6-0c3b9b0d1c3b.png)

**Comment by jofran42** [comment]
![image](https://user-images.githubusercontent.com/67721037/190884320-eb1901ff-52ba-4381-a547-59c99ed06851.png)
