### ISSUE TITLE
Mensaje final

### ISSUE THREAD

**Issue by cabudui** [jfraan/TriviaIA#5]
En el mensaje final podrias usar la variable del puntaje para mostrar cuanto fue el puntaje final y un if si saque al menos mas de 10 puntos y else si es menos

![image](https://user-images.githubusercontent.com/113648766/190837966-31df3598-97d2-4cb3-a84d-6df8df419121.png)

**Comment by jofran42** [comment]
![image](https://user-images.githubusercontent.com/67721037/190884429-eaf69f4f-1516-4849-b3f1-1a480e4520e6.png)
![image](https://user-images.githubusercontent.com/67721037/190884387-d6cb9257-92d1-4da7-b0c5-d4d03f71e01f.png)
